### ISSUE TITLE
failing validation due to not nullable property

### ISSUE THREAD

**Issue by saritapradhan07** [nori-dot-eco/nori-dot-com#36]
We don't have data for below item in Truterra metric. So validation is failing due to not null. Could you please make these properties nullable.
AnnualCropHarvestEvent:Date
{ keyword: 'type',
       dataPath: '/fields/0/cropYears/0/crops/0/harvestEvents/0/date',
       schemaPath: '#/definitions/AnnualCropHarvestEvent/properties/date/type',
       params: [Object],
       message: 'should be string' },

OrganicMatterEvent:Carbonnitrogenratio
OrganicMatterEvent:Percentmoisture
historicLandManagement

{ keyword: 'type',
       dataPath: '/fields/0/historicLandManagement',
       schemaPath: '#/definitions/HistoricNonCRPLandManagement/type',
       params: [Object],
       message: 'should be object' },
     { keyword: 'type',
       dataPath: '/fields/0/historicLandManagement',
       schemaPath: '#/definitions/HistoricCRPLandManagement/type',
       params: [Object],
       message: 'should be object' },
     { keyword: 'anyOf',
       dataPath: '/fields/0/historicLandManagement',
       schemaPath: '#/properties/historicLandManagement/anyOf',
       params: {},
       message: 'should match some schema in anyOf' } ] }

**Comment by jaycenhorton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address specification issue raised on public github repo](https://trello.com/c/Htfk257c/1824-address-specification-issue-raised-on-public-github-repo)

**Comment by jaycenhorton** [comment]
Thanks for reporting this @saritapradhan07 

This should be addressed with a combination of #35 and #38

**Comment by saritapradhan07** [comment]
Is harvest dates nullable done ? Still getting validation issue for this.

**Comment by jaycenhorton** [comment]
@saritapradhan07 the changes were not merged at the time of your post. They have since been merged and you can find the changes in v1.1.0.
